### ISSUE TITLE
Support for Admob Mediation

### ISSUE THREAD

**Issue by xmorpher** [HaxeExtension/extension-admob#19]
I'm not sure if the extension supports Admob Mediation?
(or has plans to support it in the future?)

**Comment by fbricker** [comment]
Hi, currently it does not support mediation. I hope to add it in the future, since I don't have time right now.

If someone want's to make it, please send a pull request and I'll check it 👍

**Comment by man2** [comment]
i want to make it.. let's see if i can make PR today

**Comment by man2** [comment]
submitted PR

**Comment by fbricker** [comment]
Thanks for your PR 👍 
There's now an official branch for this based on your PR
https://github.com/openfl/extension-admob/tree/mediation

I hope we can soon finish this and merge to main branch.

**Comment by pozirk** [comment]
Anyone interested to add Mediation support to the current version of the extension?

**Comment by pozirk** [comment]
So, I've finally checked docs about Medation.
1. Some ad sources don't require any third-party SDKs, so you just need to sign a contract with them, and mediation starts working automatically.
2. Those that require third-party SDKs should be basically integrated manually one by one. It doesn't really make much sense to me.

Here is the list of all the available ad sources for mediation:
https://developers.google.com/admob/android/choose-networks

Any questions?
