### ISSUE TITLE
get ad banner height?

### ISSUE THREAD

**Issue by ramsestom** [HaxeExtension/extension-admob#30]
Is there a way to get the ad banner height?
I thought the smart banner rule applied (https://firebase.google.com/docs/admob/android/banner) but that doesn't seems to be right on high definition screens (full HD), the banner seems to have a height > 90...
So it would be good if we could retrieve the expected banner height directly from the lib

**Comment by mastef** [comment]
I just finished making such changes - it stores the `getHeightInPixels()` into a static var which you can then check from your app.

If you're interested I can attempt a PR

**Comment by mastef** [comment]
Here's the gists :

AdMobEx.java
https://gist.github.com/mastef/e5e003b47830c867cb3da332b8f26ced/revisions

And AdMob.hx
https://gist.github.com/mastef/3d755cb5c46e4c1615ef83e81389bbcd/revisions

Note : In my case I'm just interested in the biggest possible height, so I'm not updating it if the size gets smaller again.
