### ISSUE TITLE
Admob Fails. How do I get the errorcode log?

### ISSUE THREAD

**Issue by Seebiscuit** [HaxeExtension/extension-admob#34]
I don't want to burden you with the onus of figuring out _why_ `showInterstitial` invokes my `_onInterstitialEvent` callback with a `FAILED` event. I don't know how to repo this and I'd rather not waste much time trying to figure out how.

All I want to know is this. You are logging the results of a failed interstitial event:
```
public void onAdFailedToLoad(int errorcode) {
	AdMobEx.getInstance().loadingInterstitial=false;	
	AdMobEx.getInstance().failInterstitial=true;
	reportInterstitialEvent(AdMobEx.FAILED);
	Log.d("AdMobEx","Fail to get Interstitial: "+errorcode);
}				
```
(https://github.com/openfl/extension-admob/blob/master/dependencies/admobex/src/admobex/AdMobEx.java#L208)

I'm running my app in `-debug` mode (esp doing: `lime test android -debug ...`) and getting practically al `logcat` messages in my terminal. I also placed a Haxe trace on the `onInterstitialEvent` in my code, so I'm seeing things like: 
```
09-18 15:54:32.145 24190 24190 I trace   : AdmobController.hx:80: InterstitialEvent: LOADING
09-18 15:54:33.391 24190 24190 I trace   : AdmobController.hx:80: InterstitialEvent: FAILED
```

What I need is access to the `Log.d("AdMobEx","Fail to get Interstitial: "+errorcode);` message so I can get that `errorcode` and debug this further. Any help would be appreciated!

**Comment by GregorHaag** [comment]
'Log.d' logs it as debug message and i think by default you wont see those in adb logcat.
You could change to 'Log.e' or show debug messages in your logcat  with 'adb logcat *:D'
