### ISSUE TITLE
Is this affect it or we are good !

### ISSUE THREAD

**Issue by Gamezpedia** [HaxeExtension/extension-admob#35]
![image](https://user-images.githubusercontent.com/1169093/33194666-56332404-d0f3-11e7-9873-2f7516488df2.png)

**Comment by pozirk** [comment]
Should be good, cause extension is using Google Play Services 9.6 or something.
You should look into **extension-googleplayservices-basement**, it contains required sdk.
You can also update it to the latest version yourself:

> To find classes.jar go to:
> %ANDROID_SDK%/extras/google/m2repository/com/google/android/gms/play-services-XXX
> 
> Get the last version AAR file.
> Unzip it!

**Comment by Gamezpedia** [comment]
thank you for the help :)
