### ISSUE TITLE
After resolving gradle using marven, I am stucked here, please help.

### ISSUE THREAD

**Issue by justnajm** [HaxeExtension/extension-admob#37]
First I was getting this error: http://community.openfl.org/t/google-play-services-lib/8078/2

I used "player_03" solution and compilation went properly but after 7/7 task it stucks here all the time :(

* What went wrong:
Execution failed for task ':deps:admobex:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.E
xecException: Process 'command 'D:\Android\android-sdk\build-tools\19.1.0\aapt.e
xe'' finished with non-zero exit value 1

Any help will be much appreciated as I am in middle of important admob issue.... :)

**Comment by pozirk** [comment]
Should be fixed with new update.
