### ISSUE TITLE
Cannot load ad

### ISSUE THREAD

**Issue by armadillojoe** [HaxeExtension/extension-admob#38]
I have everything set up as described in the readme, but when I open my app, I don't see any ads, and when looking at the android console I see these messages:

04-06 20:51:24.044 14401-14401/? I/Ads: Starting ad request.
04-06 20:51:24.045 14401-14401/? I/Ads: This request is sent from a test device.
04-06 20:51:24.385 1789-15309/? W/Ads: Received error HTTP response code: 403
04-06 20:51:24.391 14401-14781/? W/Ads: There was a problem getting an ad response. ErrorCode: 0
04-06 20:51:24.392 14401-14401/? W/Ads: Failed to load ad: 0

Anyone know what the issue could be?

**Comment by pozirk** [comment]
Should be fixed with new update.
