### ISSUE TITLE
Error Could not find com.google.android.gms:play-services-ads-lite:12.0.1.

### ISSUE THREAD

**Issue by stein-D** [HaxeExtension/extension-admob#41]
I tried update to latest version of Android SDK 28 and google play services 49

And I got this error : 
![ss](https://user-images.githubusercontent.com/23498954/49500316-04483980-f8a3-11e8-9cfa-8d5218b0e31d.png)

**Comment by Akayashi** [comment]
same issue, any solutions?

**Comment by pozirk** [comment]
Should be fixed with new update.
