### ISSUE TITLE
Crash on some android phones

### ISSUE THREAD

**Issue by Tembac** [HaxeExtension/extension-admob#42]
It was crashing on some android phones: Huawei P9 lite and Samsung Galaxy A8 

Finally, I found the problem for Huawei P9lite. It was something to do with the theme on the manifest.
I took this line out and it is now working fine:

android:theme="@android:style/Theme.Translucent"

I found the solution on this post: https://stackoverflow.com/questions/52634787/activity-intent-to-navigation-drawer-activity-app-crashes

**Comment by Tembac** [comment]
on Samsung galaxy A8 the issue is thw following:

`02-04 17:55:20.152 18482 18482 E AndroidRuntime: FATAL EXCEPTION: main
02-04 17:55:20.152 18482 18482 E AndroidRuntime: Process: com.tembac.nothingClickerTesting, PID: 18482
02-04 17:55:20.152 18482 18482 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tembac.nothingClickerTesting/com.google.android.gms.ads.AdActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
02-04 17:55:20.152 18482 18482 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
02-04 17:55:20.152 18482 18482 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
02-04 17:55:20.152 18482 18482 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
02-04 17:55:20.152 18482 18482 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
02-04 17:55:20.152 18482 18482 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
02-04 17:55:20.152 18482 18482 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
02-04 17:55:20.152 18482 18482 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
02-04 17:55:20.152 18482 18482 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-04 17:55:20.152 18482 18482 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
02-04 17:55:20.152 18482 18482 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
02-04 17:55:20.152 18482 18482 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
02-04 17:55:20.152 18482 18482 E AndroidRuntime: 	at android.app.Activity.onCreate(Activity.java:1038)
02-04 17:55:20.152 18482 18482 E AndroidRuntime: 	at com.google.android.gms.ads.AdActivity.onCreate(Unknown Source:2)
02-04 17:55:20.152 18482 18482 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7183)
02-04 17:55:20.152 18482 18482 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
02-04 17:55:20.152 18482 18482 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
02-04 17:55:20.152 18482 18482 E AndroidRuntime: 	... 9 more`

**Comment by Tembac** [comment]
Finally to solve it on both devices I deleted all the activity from the manifest of the extension. My manifest is:

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.admobex">
	<application android:debuggable="::DEBUG::">
		<meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
			android:value="ca-app-pub-numbers~numbers"/>
	</application>
</manifest>
`

This seems to work fine. I hope there are no other crashes on unknown devices.

**Comment by pozirk** [comment]
I know it's been awhile, but could you please try updated extension?
