### ISSUE TITLE
invalid application ID

### ISSUE THREAD

**Issue by CocosGames** [HaxeExtension/extension-admob#58]
![image](https://github.com/user-attachments/assets/91521221-733c-47f4-818f-2d9cb569ae61)

I keep getting this error, but I think my settings are ok... Anyone who knows why?

![image](https://github.com/user-attachments/assets/77d8cba9-42fd-49ba-a4ea-0de1a1545688)

![image](https://github.com/user-attachments/assets/95282238-3577-42f3-bd2e-7cbea303b961)

**Comment by CocosGames** [comment]
A working demo / sample project is welcome.

**Comment by MAJigsaw77** [comment]
You need to set the env name to `ADMOB_APPID` in order to set the application's id

**Comment by CocosGames** [comment]
> You need to set the env name to `ADMOB_APPID` in order to set the application's id

Yes thanks, it works.
